//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDapplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using CRUDapplication.Controllers;



    

    public partial class MVCregUser
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required!")]

        [StringLength(50)]
        [Display(Name = "UserName")]
        public string Uname { get; set; }


        [Required(ErrorMessage = "This field is required!")]
        [StringLength(50)]
        [EmailAddress()]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Uemail { get; set; }



        [Required(ErrorMessage = "This field is required!")]

        [StringLength(50)]
        [Display(Name = "Country")]
        public string Ucountry { get; set; }


        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                     ErrorMessage = "Entered phone format is not valid.")]
        public string Umob { get; set; }





        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required!")]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "minimum character should be 8")]
        [Display(Name = "Password")]
        public string Upwd { get; set; }


       public DateTime CreatedDate { get; set; }



      
        [Display(Name = "Profile Image:")]
        public string Uimg { get; set; }



    }

   

    }


